### PR TITLE
Added Repaint option to Vehicle and General stores

### PR DESCRIPTION
**Pull request by daredev**
On one of the random servers I saw this functionality on Tanoa, so I've tried to hook it up with Altis mission. I've tested it on my server running Linux w/ extDB3 and it works great.

### CODE REVIEW

**Comment by WhatsUpDoc127** [comment]
Yep we've been using this for sometime now. Works good except for some Vest will not be repainted. I haven't look at the script yet to see why...

**Comment by daredev** [comment]
Yes, I saw that. It didn't paint my Tron suit, but that's okay. It didn't break anything, so that's good.

**Comment by hobart666** [comment]
Yea, we've had this in altis and tanoa and chern and stratis since LouD's old commits a couple years ago. Good Stuff.

**Comment by daredev** [comment]
@hobart666 is there any Chernarus version available?

**Comment by hobart666** [comment]
I think I have a very old chern wasteland mission somewhere, but it would need to be updated to the new commits, It would probably be easier to use a new copy of vanilla and convert it to chern.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/b8c5e20df6ac1419a970691a9eaf0cdf9a1904e5

**Pull request closed without merging**
