### PR TITLE
Stop _realLoopTime spam

### PR DESCRIPTION
**Pull request by nerdalertdk**
I like my RTP clean, when runing prod

### CODE REVIEW

**Comment by AgentRev** [comment]
`DEBUG` is undefined

**Comment by nerdalertdk** [comment]
from init.sqf

#ifdef A3W_DEBUG
#define DEBUG true
#else
#define DEBUG false
#endif

ARG..... discoverts the #

http://icrontic.com/uploads/features/tech/2011/09/nothing_to_see_here-300x238.jpg

**Comment by nerdalertdk** [comment]
Well lets try again :)

**Comment by AgentRev** [comment]
no, you can't refer to defines like that, they are not included in the file. just comment out the diag_log and I'll merge.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/d77ac09b2cdeb2c0f55bf0b7cb731ead4f68e82a

**Pull request closed without merging**
