### PR TITLE
Store Fix, Tropical CFG

### PR DESCRIPTION
**Pull request by ShineDwarf**
Swap out Apex version for stock version to align with missions for proper sell prices

### CODE REVIEW

**Comment by AgentRev** [comment]
good catch, definitely unintended

**Comment by ShineDwarf** [comment]
That took me 2 weeks of looking for rpt errors, comparing sqfs, and general wtf's to find. It wasnt limited to those 2 vehicles on our server so it wasnt apparent. I had tropical vehicles in missions too. Stupid bohemia, just add a damn skin.

**Comment by AgentRev** [comment]
Dang, sorry lol, I tried as possible to match all the classes, but I never noticed the Angara was wrong because I always buy it with a custom paintjob

**Comment by ShineDwarf** [comment]
Definitely not your fault. Under normal circumstances, it wouldn't be an issue xD Thanks for all the hard-work btw. our members are always appreciative

**Pull request merged**
